name: Tor Setup and Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-tor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Tor and Torsocks
      run: |
        sudo apt update
        sudo apt install -y tor torsocks

    - name: Configure torrc
      run: |
        sudo bash -c 'cat > /etc/tor/torrc <<EOF
        SocksPort 9050
        Log notice stdout
        EOF'

    - name: Start Tor
      run: |
        sudo systemctl restart tor
        sleep 10
        sudo journalctl -u tor --no-pager | tail -n 20


    - name: Start Reg
      run: |
        sudo sh faucet.sh
